# Backup + restore of qBittorrent's per-torrent state (BT_backup: .torrent +
# .fastresume), categories/tags/watched folders (config/) and RSS state (rss/).
# Everything else in the profile is regenerated by the qbittorrent module's
# preStart (qBittorrent.conf) or is scratch (logs). Mirrors the plex-backup /
# arr-restore pattern: a daily timer writes tarballs to a mounted NAS share,
# qbittorrent-restore pulls the newest one back after a teardown.
{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.services.qbittorrent-vpn;
  bcfg = cfg.backup;
  profile = "/var/lib/qbittorrent/qBittorrent";

  backupScript = pkgs.writeShellApplication {
    name = "qbittorrent-backup";
    runtimeInputs = [pkgs.coreutils pkgs.findutils pkgs.gnutar pkgs.gzip pkgs.util-linux];
    text = ''
      PROFILE=${escapeShellArg profile}
      BACKUP=${escapeShellArg bcfg.dir}
      RETENTION=${toString bcfg.retention}

      if ! mountpoint -q "$BACKUP"; then
        echo "qbittorrent-backup: backup share $BACKUP is not mounted; aborting." >&2
        exit 1
      fi
      if [ ! -d "$PROFILE/BT_backup" ]; then
        echo "qbittorrent-backup: $PROFILE/BT_backup does not exist (no torrents yet); nothing to back up."
        exit 0
      fi
      # A freshly recreated profile (recovery before/without its restore) has an
      # empty BT_backup; archiving it would put an empty snapshot at the top of
      # the list — which is what the next restore attempt would pick — and rotate
      # the real ones out. Skip instead of writing.
      if [ "$(find "$PROFILE/BT_backup" -name '*.fastresume' | wc -l)" -eq 0 ]; then
        echo "qbittorrent-backup: no torrents in $PROFILE/BT_backup; refusing to write an empty archive over the existing ones."
        exit 0
      fi

      # Clear staging files left behind by a previously interrupted run.
      rm -f "$BACKUP"/.qbittorrent-backup-*.partial

      stamp="$(date +%Y%m%d-%H%M%S)"
      staging="$BACKUP/.qbittorrent-backup-$stamp.partial"
      dest="$BACKUP/qbittorrent-backup-$stamp.tar.gz"

      members=(BT_backup)
      [ -d "$PROFILE/config" ] && members+=(config)
      [ -d "$PROFILE/rss" ] && members+=(rss)

      # qBittorrent writes each .fastresume atomically, so a live tar is a
      # consistent per-torrent snapshot; --ignore-failed-read rides out a file
      # replaced mid-archive instead of discarding the whole run.
      tar --ignore-failed-read --warning=no-file-changed -C "$PROFILE" -czf "$staging" "''${members[@]}"
      if ! tar -tzf "$staging" >/dev/null; then
        echo "qbittorrent-backup: ERROR archive verification failed; discarding $staging" >&2
        rm -f "$staging"
        exit 1
      fi
      mv -f "$staging" "$dest"
      echo "qbittorrent-backup: wrote $dest ($(find "$PROFILE/BT_backup" -name '*.fastresume' | wc -l) torrent(s))"

      # Retention — keep only the newest $RETENTION archives.
      mapfile -t archives < <(find "$BACKUP" -maxdepth 1 -type f -name 'qbittorrent-backup-*.tar.gz' | sort)
      total=''${#archives[@]}
      if [ "$total" -gt "$RETENTION" ]; then
        prune=$((total - RETENTION))
        for ((i = 0; i < prune; i++)); do
          echo "qbittorrent-backup: pruning old archive ''${archives[i]}"
          rm -f "''${archives[i]}"
        done
      fi
      echo "qbittorrent-backup: done."
    '';
  };

  restoreScript = pkgs.writeShellApplication {
    name = "qbittorrent-restore";
    runtimeInputs = [pkgs.coreutils pkgs.findutils pkgs.gnutar pkgs.gzip pkgs.util-linux pkgs.curl];
    text = ''
      PROFILE=${escapeShellArg profile}
      BACKUP=${escapeShellArg bcfg.dir}
      SERVICE=qbittorrent.service
      WEBUI="http://10.200.200.2:${toString cfg.webUI.port}/api/v2/app/version"

      usage() {
        cat <<USAGE
      qbittorrent-restore — restore qBittorrent torrent state from $BACKUP

        qbittorrent-restore               restore the newest archive
        qbittorrent-restore --list        list available archives (newest first), exit
        qbittorrent-restore --from <tar>  restore from a specific archive
        qbittorrent-restore --help        show this help
      USAGE
      }

      list_backups() {
        [ -d "$BACKUP" ] || return 0
        find "$BACKUP" -maxdepth 1 -type f -name 'qbittorrent-backup-*.tar.gz' -printf '%T@ %p\n' 2>/dev/null |
          sort -rn | cut -d' ' -f2-
      }

      orig_args=("$@")
      from=""
      while [ $# -gt 0 ]; do
        case "$1" in
          --list) list_backups; exit 0 ;;
          --from)
            shift
            from="''${1:-}"
            if [ -z "$from" ]; then
              echo "qbittorrent-restore: --from requires an archive path." >&2
              exit 1
            fi
            shift
            ;;
          -h | --help) usage; exit 0 ;;
          *)
            echo "qbittorrent-restore: unknown argument: $1" >&2
            usage >&2
            exit 1
            ;;
        esac
      done

      if [ "$(id -u)" -ne 0 ]; then
        exec sudo -- "$0" "''${orig_args[@]}"
      fi

      if ! mountpoint -q "$BACKUP"; then
        echo "qbittorrent-restore: backup share $BACKUP is not mounted; aborting." >&2
        exit 1
      fi

      # --- Resolve + validate BEFORE touching the live service. ---
      if [ -n "$from" ]; then
        archive="$from"
      else
        archive="$(list_backups | head -1)"
      fi
      if [ -z "$archive" ]; then
        # A share with no archive is the normal state of a FIRST install (nothing
        # has ever been backed up) — that is "nothing to restore", not a failure.
        # Exiting 0 lets the first-boot unit stamp itself done, so a later reboot
        # cannot restore the first daily archive over a live torrent list. A
        # corrupt archive or an unmounted share still fails (and is retried).
        echo "qbittorrent-restore: no archive (qbittorrent-backup-*.tar.gz) under $BACKUP — nothing to restore (first install?). Starting with an empty torrent list; the daily backup covers the next rebuild."
        exit 0
      fi
      if [ ! -f "$archive" ]; then
        echo "qbittorrent-restore: archive not found: $archive" >&2
        exit 1
      fi
      if ! tar -tzf "$archive" >/dev/null 2>&1; then
        echo "qbittorrent-restore: '$archive' failed its integrity check; aborting." >&2
        exit 1
      fi
      if ! tar -tzf "$archive" | grep -q '^BT_backup/'; then
        echo "qbittorrent-restore: '$archive' does not contain BT_backup/; aborting." >&2
        exit 1
      fi

      echo "qbittorrent-restore: restoring from $archive"

      # --- Apply. ---
      echo "qbittorrent-restore: stopping $SERVICE ..."
      systemctl stop "$SERVICE" || true

      install -d -o qbittorrent -g qbittorrent "$PROFILE"
      tar -C "$PROFILE" -xzf "$archive"
      chown -R qbittorrent:qbittorrent "$PROFILE"
      echo "qbittorrent-restore: restored $(find "$PROFILE/BT_backup" -name '*.fastresume' | wc -l) torrent(s)"

      # The state is on disk now, which is what this restore is for. Starting
      # the service can legitimately fail here (its WireGuard namespace needs
      # /run/hostsecrets/proton-vpn.conf, which may not be shared in yet); it
      # picks the restored torrents up whenever it does start, so that is a
      # warning, not a failed restore.
      echo "qbittorrent-restore: starting $SERVICE ..."
      if ! systemctl start "$SERVICE"; then
        echo "qbittorrent-restore: WARNING $SERVICE did not start (check 'systemctl status $SERVICE' and the VPN namespace); the restored torrents load on its next successful start." >&2
        echo "qbittorrent-restore: done."
        exit 0
      fi

      # --- Best-effort post-start check (the WebUI lives in the VPN netns, reachable over the veth). ---
      ok=0
      for ((n = 0; n < 30; n++)); do
        if curl -sf "$WEBUI" >/dev/null 2>&1; then
          ok=1
          break
        fi
        sleep 1
      done
      if [ "$ok" -eq 1 ]; then
        echo "qbittorrent-restore: qBittorrent is up."
      else
        echo "qbittorrent-restore: WARNING qBittorrent did not answer on $WEBUI within 30s; check 'systemctl status $SERVICE'." >&2
      fi
      echo "qbittorrent-restore: done."
    '';
  };
in {
  options.services.qbittorrent-vpn.backup = {
    enable = mkEnableOption "scheduled backups of qBittorrent's torrent state to a mounted share, plus the qbittorrent-restore command";

    dir = mkOption {
      type = types.str;
      default = "/mnt/backups/qbittorrent";
      description = "Mounted backup share the archives are written to (and restored from). Mount it with `fileSystems`; the units wait for it via RequiresMountsFor.";
    };

    retention = mkOption {
      type = types.ints.positive;
      default = 7;
      description = "Number of archives to keep.";
    };

    onCalendar = mkOption {
      type = types.str;
      default = "daily";
      description = "systemd OnCalendar schedule for the backup timer.";
    };
  };

  config = mkIf (cfg.enable && bcfg.enable) {
    environment.systemPackages = [backupScript restoreScript];

    systemd.services.qbittorrent-backup = {
      description = "Back up qBittorrent torrent state to the NAS";
      unitConfig.RequiresMountsFor = bcfg.dir;
      serviceConfig = {
        Type = "oneshot";
        User = "qbittorrent";
        Group = "qbittorrent";
        ExecStart = "${backupScript}/bin/qbittorrent-backup";
      };
    };

    systemd.timers.qbittorrent-backup = {
      description = "Scheduled qBittorrent backup";
      wantedBy = ["timers.target"];
      timerConfig = {
        OnCalendar = bcfg.onCalendar;
        Persistent = true;
        RandomizedDelaySec = "30m";
      };
    };
  };
}
